name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Run migrations
      run: php artisan migrate --force

    - name: Deploy to server
      run: |
        ssh username@yourserver.com "cd /path/to/your/laravel/project && git pull origin main && php artisan migrate --force"
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
